spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-service
    username: postgres
    password: postgres

server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:8080
  realm-resource: task-tracker
  admin-client:
    client-id: admin-api
    client-secret: Nz9xbavugnibdv2PJ0eSa2wIzJi1s0Md
  frontend-client:
    client-id: auth-service
    client-secret: syMTilWPqGXH7sGzs5yiq498O95IYDut