services:
  auth_postgres:
    image: postgres:latest
    container_name: auth_postgres
    environment:
      POSTGRES_USER: ${AUTH_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_SERVICE_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: "false"
      KC_DB: dev-file
    command: start-dev
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/live" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth-service
    image: lemoonier/auth-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      AUTH_SERVICE_POSTGRES_USER: ${AUTH_SERVICE_POSTGRES_USER}
      AUTH_SERVICE_POSTGRES_PASSWORD: ${AUTH_SERVICE_POSTGRES_PASSWORD}
      AUTH_SERVICE_POSTGRES_DB: ${AUTH_SERVICE_POSTGRES_DB}
      KEYCLOAK_AUTH_SERVER_URL: ${KEYCLOAK_AUTH_SERVER_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_ADMIN_CLIENT_ID: ${KEYCLOAK_ADMIN_CLIENT_ID}
      KEYCLOAK_ADMIN_CLIENT_SECRET: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
      KEYCLOAK_FRONTEND_CLIENT_ID: ${KEYCLOAK_FRONTEND_CLIENT_ID}
      KEYCLOAK_FRONTEND_CLIENT_SECRET: ${KEYCLOAK_FRONTEND_CLIENT_SECRET}
    ports:
      - "8081:8080"

volumes:
  auth_postgres_data:

networks:
  app-network:
    driver: bridge