spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/task-service
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9094

server:
  port: 8082

keycloak:
  auth-server-url: http://localhost:8080
  realm-resource: task-tracker

app:
  kafka:
    topics:
      task-created: task-created-topic
      task-status-changed: task-status-changed-topic