spring:
  datasource:
    url: jdbc:postgresql://task_postgres:5432/${TASK_SERVICE_POSTGRES_DB:task_db}
    username: ${TASK_SERVICE_POSTGRES_USER:postgres}
    password: ${TASK_SERVICE_POSTGRES_PASSWORD:postgres}

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  realm-resource: ${KEYCLOAK_REALM}
spring:
  datasource:
    url: jdbc:postgresql://task_postgres:5432/${TASK_SERVICE_POSTGRES_DB:task_db}
    username: ${TASK_SERVICE_POSTGRES_USER:postgres}
    password: ${TASK_SERVICE_POSTGRES_PASSWORD:postgres}

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  realm-resource: ${KEYCLOAK_REALM}